---
title: "fitness_function"
author: "Robert Jankowski"
date: "12/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

```{r}
data <- read.csv("logs_run_92.csv", header = F)
colnames(data) <- c("t", "n", "mean", "min", "max")
data$t <- as.POSIXct(data$t, format = "%m-%d-%Y_%H-%M", origin="1970-01-01", tz="GMT")
head(data)
```

```{r}

```


```{r, info = F, message=F}
p <- ggplot(data) + 
  geom_point(aes(n, mean, color = "mean"), alpha=0.1) +
  geom_point(aes(n, min, color = "min"), alpha=0.1) +
  geom_point(aes(n, max, color = "max"), alpha=0.1) +
  geom_smooth(aes(n, mean, color = "mean"), alpha=0.4) +
  geom_smooth(aes(n, min, color = "min"), alpha=0.4) +
  geom_smooth(aes(n, max, color = "max"), alpha=0.4) +
  theme_light() +
  labs(x = "generation", y = "fitness score") + 
  scale_color_discrete(labels = c("max", "mean", "min")) +
  theme(legend.position = "top", 
        legend.title = element_blank(), legend.text = element_text(size = 13), 
        text = element_text(size = 14))

# ggsave("fitness_function.png", p, width = 6, height = 4)
p
```

